// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: braingain.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Braingain_Chat_FullMethodName            = "/endpoint.braingain.v1.Braingain/Chat"
	Braingain_FindDocuments_FullMethodName   = "/endpoint.braingain.v1.Braingain/FindDocuments"
	Braingain_ListCollections_FullMethodName = "/endpoint.braingain.v1.Braingain/ListCollections"
	Braingain_IndexDocument_FullMethodName   = "/endpoint.braingain.v1.Braingain/IndexDocument"
)

// BraingainClient is the client API for Braingain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BraingainClient interface {
	Chat(ctx context.Context, in *Prompt, opts ...grpc.CallOption) (*Completion, error)
	FindDocuments(ctx context.Context, in *DocumentQuery, opts ...grpc.CallOption) (*Documents, error)
	ListCollections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Collections, error)
	IndexDocument(ctx context.Context, in *StorageRef, opts ...grpc.CallOption) (Braingain_IndexDocumentClient, error)
}

type braingainClient struct {
	cc grpc.ClientConnInterface
}

func NewBraingainClient(cc grpc.ClientConnInterface) BraingainClient {
	return &braingainClient{cc}
}

func (c *braingainClient) Chat(ctx context.Context, in *Prompt, opts ...grpc.CallOption) (*Completion, error) {
	out := new(Completion)
	err := c.cc.Invoke(ctx, Braingain_Chat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *braingainClient) FindDocuments(ctx context.Context, in *DocumentQuery, opts ...grpc.CallOption) (*Documents, error) {
	out := new(Documents)
	err := c.cc.Invoke(ctx, Braingain_FindDocuments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *braingainClient) ListCollections(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Collections, error) {
	out := new(Collections)
	err := c.cc.Invoke(ctx, Braingain_ListCollections_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *braingainClient) IndexDocument(ctx context.Context, in *StorageRef, opts ...grpc.CallOption) (Braingain_IndexDocumentClient, error) {
	stream, err := c.cc.NewStream(ctx, &Braingain_ServiceDesc.Streams[0], Braingain_IndexDocument_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &braingainIndexDocumentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Braingain_IndexDocumentClient interface {
	Recv() (*IndexProgress, error)
	grpc.ClientStream
}

type braingainIndexDocumentClient struct {
	grpc.ClientStream
}

func (x *braingainIndexDocumentClient) Recv() (*IndexProgress, error) {
	m := new(IndexProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BraingainServer is the server API for Braingain service.
// All implementations must embed UnimplementedBraingainServer
// for forward compatibility
type BraingainServer interface {
	Chat(context.Context, *Prompt) (*Completion, error)
	FindDocuments(context.Context, *DocumentQuery) (*Documents, error)
	ListCollections(context.Context, *emptypb.Empty) (*Collections, error)
	IndexDocument(*StorageRef, Braingain_IndexDocumentServer) error
	mustEmbedUnimplementedBraingainServer()
}

// UnimplementedBraingainServer must be embedded to have forward compatible implementations.
type UnimplementedBraingainServer struct {
}

func (UnimplementedBraingainServer) Chat(context.Context, *Prompt) (*Completion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedBraingainServer) FindDocuments(context.Context, *DocumentQuery) (*Documents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDocuments not implemented")
}
func (UnimplementedBraingainServer) ListCollections(context.Context, *emptypb.Empty) (*Collections, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedBraingainServer) IndexDocument(*StorageRef, Braingain_IndexDocumentServer) error {
	return status.Errorf(codes.Unimplemented, "method IndexDocument not implemented")
}
func (UnimplementedBraingainServer) mustEmbedUnimplementedBraingainServer() {}

// UnsafeBraingainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BraingainServer will
// result in compilation errors.
type UnsafeBraingainServer interface {
	mustEmbedUnimplementedBraingainServer()
}

func RegisterBraingainServer(s grpc.ServiceRegistrar, srv BraingainServer) {
	s.RegisterService(&Braingain_ServiceDesc, srv)
}

func _Braingain_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Prompt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BraingainServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Braingain_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BraingainServer).Chat(ctx, req.(*Prompt))
	}
	return interceptor(ctx, in, info, handler)
}

func _Braingain_FindDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BraingainServer).FindDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Braingain_FindDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BraingainServer).FindDocuments(ctx, req.(*DocumentQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Braingain_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BraingainServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Braingain_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BraingainServer).ListCollections(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Braingain_IndexDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StorageRef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BraingainServer).IndexDocument(m, &braingainIndexDocumentServer{stream})
}

type Braingain_IndexDocumentServer interface {
	Send(*IndexProgress) error
	grpc.ServerStream
}

type braingainIndexDocumentServer struct {
	grpc.ServerStream
}

func (x *braingainIndexDocumentServer) Send(m *IndexProgress) error {
	return x.ServerStream.SendMsg(m)
}

// Braingain_ServiceDesc is the grpc.ServiceDesc for Braingain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Braingain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "endpoint.braingain.v1.Braingain",
	HandlerType: (*BraingainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _Braingain_Chat_Handler,
		},
		{
			MethodName: "FindDocuments",
			Handler:    _Braingain_FindDocuments_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _Braingain_ListCollections_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IndexDocument",
			Handler:       _Braingain_IndexDocument_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "braingain.proto",
}
